version: 2.1

executors:
  node-executor:
    docker:
    - image: circleci/node:9.9
    working_directory: ~/webapp
jobs:
  install-dependencies:
    executor: node-executor
    working_directory: ~/webapp

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run: npm install

      - persist_to_workspace:
        root: ~/webapp
        paths:
          - node_modules

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

workflows:
  version: 2
  github_pipeline:
    jobs:
      - install-dependencies
      - test:
          requires:
          -install-dependencies
      - lint:
          requires:
          - innstall-dependencies
      - build-client-github
          requires:
          - install-dependencies
          filters:
            branches:
              only: master
      - deploy-github
          requires:
          - build-client-github
          - lint
          - test
          filters:
            branches:
              only: master
